USE pacifiko
--1. Insert a new product with the following details: Product Name: "Laptop", Price: 1000.00,Stock Quantity: 50.
INSERT INTO Products (product_name,price,stock_quantity)
VALUES('Laptop',1000.00,50);

--2. Update the stock quantity of the product with product_id = 3 to 75.
UPDATE Products
SET stock_quantity = 75
WHERE product_id = 3;

--3. Delete the order with order_id = 10 and its associated order items
DELETE FROM OrderItems
WHERE order_id = 10;

DELETE FROM Orders
WHERE order_id = 10;


--4. Retrieve the customer's first and last names who placed the order with order_id = 5
SELECT first_name,
last_name
FROM Customers C WITH(NOLOCK) INNER JOIN Orders O WITH(NOLOCK) ON C.customer_id = O.customer_id
WHERE O.order_id = 5;


--5. Calculate the total revenue generated by each product (sum of subtotals from order  items).
SELECT SUM(I.subtotal), O.product_name, O.product_id
 FROM OrderItems I WITH(NOLOCK) INNER JOIN Products O WITH(NOLOCK) ON I.product_id = O.product_id
 GROUP BY O.product_name, O.product_id
 ORDER BY SUM(I.subtotal) DESC;